apiVersion: v1
kind: Namespace
metadata:
  name: issue-tracker
  labels:
    name: issue-tracker

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-Config
  namespace: issue-tracker
data:
  NODE_ENV: "production"
  REACT_APP_API_URL: "http://localhost:8080/api"
